### ISSUE TITLE
Money theft

### ISSUE THREAD

**Issue by installgen2** [zetok/stqism#3]
I'm not sure what happened, but I've heard that stqism may have stolen money, and I think it would only be appropriate to have information here!

**Comment by zetok** [comment]
>and I think it would only be appropriate to have information here!

That may be.

Consider though that this is still an open matter, and things aren't exactly settled - @stqism and @irungentoo are going to talk about it during Saturday, and most likely there will be blog post about things after that.

The way I see things, there's no point in putting here anything yet.. And considering that there should be blog post made, most likely there will be no need.

No need, since @stqism won't be any longer a part of Tox, and this repo was created to provide info how he was actively harming it.

As for money - while @stqism did take money, he's paying it back to @irungentoo, bit by bit.

If what I wrote about this satisfies you, please close the issue.. if not really - wait for blog post, and see if it will satisfy you.

**Comment by installgen2** [comment]
>@stqism won't be any longer a part of Tox
yay!

If there is going to be a  blog post, I'll just wait to find out what is going on when it is released, closing issue.

**Comment by im-grey** [comment]
>@stqism won't be any longer a part of Tox

Thank fuck.

**Comment by ProMcTagonist** [comment]
Awaiting a post from gentoo explaining the situation.

**Comment by truuuu** [comment]
it doesn't matter if Sean "leaves"
he and irungentoo are in this together, they know each other personally and the fact irungentoo didn't kick stqism out of tox when ALL other devs agreed he was bad for the project shows the bias.
as long as tox foundation exists and irungentoo (with sean undercover helping) run things in this grossly unethical (even illegal, google embezzling" it's all lost.
it's time to stop supporting tox

**Comment by zetok** [comment]
@truuuu do you have anything other than FUD?

You seem pretty confident of what you're saying - mind providing sources supporting that bullshit?

Points that I would like further info on:

>he and irungentoo are in this together, they know each other personally and the fact irungentoo didn't kick stqism out of tox when ALL other devs agreed he was bad for the project shows the bias.

* So, stq doesn't pay @irungentoo his money back, holds Tox domains hostage, doesn't answer to anyone, etc, and you're blaming victim, @irungentoo for trying to do what he could to at least get from stq domains back, so that least amount of people would be affected by shit?

* Additionally, mind providing your source on “ALL other devs agreed he was bad for the project” ? Do you know why this repo even exists? It was made to make people aware of stq shit precisely because **people didn't see anything wrong with him being a part of Tox**. Now, if you could provide source of your claims, I would be really interested in hearing how **everyone** was against stq… Or do you simply enjoy throwing shit at the person who through his endless efforts (@irungentoo) made Tox possible?

(hint: stq wouldn't be a part of Tox for so long if even most of people agreed that he's bad, doesn't have to be ***everyone***)

>as long as tox foundation exists and irungentoo (with sean undercover helping) run things in this grossly unethical (even illegal, google embezzling" it's all lost.

Mind explaining that?

>it's time to stop supporting tox

Are you sure that you "support" something by spreading FUD about it?

**Comment by ProMcTagonist** [comment]
@zetok lol baleeted

![lol](https://cloud.githubusercontent.com/assets/4358079/8268177/825f9226-1730-11e5-9f97-a64faed46e00.png)

**Comment by stal888** [comment]
noice

**Comment by installgen2** [comment]
oh no what have I begun ;-;

**Comment by zetok** [comment]
https://blog.tox.chat/2015/07/current-situation-3/ ← took way too long, but here it is.
